const filters = {
    blur: {
      text: "Blur Radius",
      min: 0,
      max: 10,
      initValue: 0,
      unit: "px",
    },
    brightness: {
      text: "Brightness",
      min: 0,
      max: 200,
      initValue: 100,
      unit: "%",
    },
    contrast: {
      text: "Contrast",
      min: 0,
      max: 200,
      initValue: 100,
      unit: "%",
    },
    grayscale: {
      text: "Grayscale",
      min: 0,
      max: 100,
      initValue: 0,
      unit: "%",
    },
    invert: {
      text: "Invert",
      min: 0,
      max: 100,
      initValue: 0,
      unit: "%",
    },
    opacity: {
      text: "Opacity",
      min: 0,
      max: 100,
      initValue: 100,
      unit: "%",
    },
    saturate: {
      text: "Saturate",
      min: 0,
      max: 200,
      initValue: 100,
      unit: "%",
    },
    sepia: {
      text: "Sepia",
      min: 0,
      max: 100,
      initValue: 0,
      unit: "%",
    },
    "hue-rotate": {
      text: "Hue Rotate",
      min: 0,
      max: 360,
      initValue: 0,
      unit: "deg",
    },
  };